### PR TITLE
Renamed MaxLifeTime as MaxAnimationLifeTime and moved it from the imp…

### PR DESCRIPTION
**Pull request by edwinyzh**
…lementation section to the interface section, so that one can perform checking against it to avoid exception error messsages such as 'Delay (11000) must be lower than MaxLifeTime (10000)'

And fixed a typo.

### CODE REVIEW

**Review by WladiD — CHANGES_REQUESTED** [review]
Hi Edwin,

the move from implementation to interface section is a good point, if you want to check the max value anywhere. But the new name MaxAnimationLifeTime is misleading, because this const is not only for animations but for the whole garbage collection background work.

Do you want to roll back the rename? Then the merge can happen.

Thank you and best regards from Germany!

**Comment by edwinyzh** [comment]
@WladiD, I see. Done the amendment. Thanks for this excellent lib.

**Comment by WladiD** [comment]
I'm curious to know, in what a project you use AnyiQuack. 

Anything visible on the web?

**Comment by edwinyzh** [comment]
Among other things, I mostly use the notification window, it works very well, see a screenshot: https://screenpresso.com/=0Sp9e

Overall You have achieved a really smooth and versatile  VCL animation mechanism.

**Comment by WladiD** [comment]
Very nice!

Thanks for your kudo and feedback!

**Pull request merged**
